### ISSUE TITLE
应该加到Hexo的Plugin List里

### ISSUE THREAD

**Issue by NoahDragon** [Menci/hexo-deployer-upyun#1]
https://hexo.io/plugins/

**Comment by Menci** [comment]
It's here!

![screenshot from 2016-12-18 10 34 24](https://cloud.githubusercontent.com/assets/11341955/21291072/94cccbcc-c50d-11e6-8bf4-5155b7f9ee00.png)

**Comment by NoahDragon** [comment]
...看来我的页面cache了，竟然没有看到

**Comment by Menci** [comment]
qnq
