### ISSUE TITLE
大佬您好，请问这个报错怎么解决啊

### ISSUE THREAD

**Issue by Aesrium** [Menci/hexo-deployer-upyun#7]
试了好几遍都没成功，文件夹倒是全都建好了，但一个文件都没传上去

![](https://cdn.jsdelivr.net/gh/xiao-lin52/image-upload/20210208124034.png)

**Comment by Menci** [comment]
什么版本的 hexo，新的可能需要 https://github.com/abcdGJJ/hexo-deployer-upyun2019 这个

也可能是网络问题，检查一下能不能连的上 upyun 的 api endpoint

**Comment by Aesrium** [comment]
谢谢大佬，这下行了，应该是 Hexo 版本的问题，我用的是 5.3.0
